import {Config} from './interfaces';

export const config: Config = {
  KEYCLOAK_URL: window.KEYCLOAK_URL,
  KEYCLOAK_REALM: window.KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_ID: window.KEYCLOAK_CLIENT_ID,
  KEYCLOAK_REDIRECT_URI: window.KEYCLOAK_REDIRECT_URI,
  OPEN_FORMS_URL: window.OPEN_FORMS_URL,
  OPEN_FORMS_FORM_ID: window.OPEN_FORMS_FORM_ID,
  OPEN_FORMS_BASE_PATH: window.OPEN_FORMS_BASE_PATH,
  OPEN_FORMS_SDK_JS: window.OPEN_FORMS_SDK_JS,
  OPEN_FORMS_SDK_CSS: window.OPEN_FORMS_SDK_CSS,
  FORM_NAME: window.FORM_NAME,
  GRAPHQL_URI: window.GRAPHQL_URI,
  REST_URI: window.REST_URI,
};
